# Generated by Django 6.0.7 on 2026-07-15 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='code',
            field=models.CharField(db_index=True, max_length=10, unique=True, verbose_name='Kod'),
        ),
        migrations.AlterField(
            model_name='department',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='E-posta'),
        ),
        migrations.AlterField(
            model_name='department',
            name='floor',
            field=models.CharField(blank=True, max_length=50, verbose_name='Kat / Blok'),
        ),
        migrations.AlterField(
            model_name='department',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Sıralama'),
        ),
        migrations.AlterModelTable(
            name='department',
            table='departments',
        ),
    ]
